#!/usr/bin/env python3
"""
IOM Data Cleaning Script
========================

This script processes raw IOM Excel data files and produces clean, validated CSV files.

Input files:
    - ALL MED DATA 2010-2025_12.08.2025.xlsx (Mediterranean crossings data)
    - IOM_MMP data_2014-2025_12.08.2025.xlsx (Missing Migrants Project data)

Output files:
    - Clean/med_crossings_monthlyTS.csv (cleaned time series)
    - Clean/iom_mmp_incidents_2014_2025_reg.csv
    - Clean/iom_mmp_2014_2025_all_types.csv
    - Clean/iom_mmp_index.csv

Author: Generated by Claude
Date: 2026-01-05
"""

import pandas as pd
import numpy as np
from pathlib import Path
import warnings

warnings.filterwarnings('ignore')


def clean_mediterranean_crossings(excel_path, output_dir):
    """
    Clean Mediterranean crossings data from Excel file.

    The Excel file has a complex structure where:
    - Year 2023 has a year marker in column 0
    - Years 2024 and 2025 do NOT have year markers
    - This causes forward-fill to incorrectly label all data as 2023

    Parameters:
    -----------
    excel_path : str or Path
        Path to the raw Excel file
    output_dir : str or Path
        Directory where cleaned CSV will be saved

    Returns:
    --------
    pd.DataFrame
        Cleaned DataFrame
    """

    print("="*70)
    print("CLEANING MEDITERRANEAN CROSSINGS DATA")
    print("="*70)

    # Read the Excel file
    print(f"\nReading Excel file: {excel_path}")
    df_excel = pd.read_excel(
        excel_path,
        sheet_name='Crossings 2014-24 ALL ROUTE',
        header=0
    )

    print(f"  Raw shape: {df_excel.shape}")

    # The actual data starts at row 2 (after headers)
    # Read again with proper header handling
    df_raw = pd.read_excel(
        excel_path,
        sheet_name='Crossings 2014-24 ALL ROUTE',
        header=None
    )

    # Extract year and month columns (columns 0 and 1)
    years_months = df_raw.iloc[3:, [0, 1]].copy()
    years_months.columns = ['Year', 'Month']

    # Forward fill years (but this is where the problem occurs for 2024/2025!)
    years_months['Year'] = years_months['Year'].ffill()

    # Remove rows with invalid months
    years_months = years_months[years_months['Month'].notna()].copy()
    years_months = years_months[~years_months['Month'].astype(str).str.contains('TOTAL', na=False)].copy()
    years_months = years_months[~years_months['Month'].astype(str).str.contains('As of', na=False)].copy()
    years_months = years_months[~years_months['Month'].astype(str).str.contains('Source', na=False)].copy()

    # Reset index to get row positions
    years_months = years_months.reset_index(drop=True)

    print(f"  Extracted {len(years_months)} month records")

    # Now we need to fix the years for rows that should be 2024 and 2025
    # Strategy: Use the Excel row structure to determine correct years

    # Create a mapping: Excel row -> Year
    # Based on analysis:
    # Rows 3-14: 2014 (12 months)
    # Rows 16-27: 2015 (12 months)
    # ...
    # Rows 120-131: 2023 (12 months)
    # Rows 133-144: 2024 (12 months) <- NO year marker!
    # Rows 146-157: 2025 (12 months) <- NO year marker!

    year_boundaries = {
        2014: (3, 14),
        2015: (16, 27),
        2016: (29, 40),
        2017: (42, 53),
        2018: (55, 66),
        2019: (68, 79),
        2020: (81, 92),
        2021: (94, 105),
        2022: (107, 118),
        2023: (120, 131),
        2024: (133, 144),
        2025: (146, 157),
    }

    # Build a comprehensive dataset by reading all necessary columns
    # Re-read with proper column extraction
    df_full = pd.read_excel(
        excel_path,
        sheet_name='Crossings 2014-24 ALL ROUTE',
        header=0
    )

    # Initialize lists to store data
    records = []

    # Process each year
    for year, (start_row, end_row) in year_boundaries.items():
        # Get data for this year (adjust for 0-indexing and header)
        year_data = df_raw.iloc[start_row:end_row+1, :].copy()

        for idx, row in year_data.iterrows():
            month_name = row[1]

            # Skip TOTAL rows and invalid months
            if pd.isna(month_name) or 'TOTAL' in str(month_name):
                continue

            # Parse month name to number
            month_map = {
                'January': 1, 'February': 2, 'March': 3, 'March  ': 3,
                'April': 4, 'May': 5, 'June': 6, 'July': 7,
                'August': 8, 'September': 9, 'September ': 9,
                'October': 10, 'November': 11, 'November ': 11, 'December': 12
            }

            month_num = month_map.get(month_name.strip() if isinstance(month_name, str) else month_name, None)

            if month_num is None:
                continue

            # Extract all column values (adjust column indices as needed)
            record = {
                'date': f"{year}-{month_num:02d}-01",
                'year': float(year),
                'month': float(month_num),
                'month_name': month_name.strip() if isinstance(month_name, str) else month_name,
                'year_2': year,
                'month_2': month_num,
            }

            # Add all data columns (columns 2 onwards)
            # Map to proper column names based on the Excel structure
            col_mapping = {
                2: 'waar',
                3: 'wmr_sea_arrivals',
                4: 'wmr_land_arrivals',
                5: 'total_sea_arrivals_waar_wmr',
                6: 'sea_arrivals_in_italy',
                7: 'sea_arrivals_in_malta',
                8: 'land_arrivals_in_greece',
                9: 'sea_arrivals_in_greece',
                10: 'sea_arrivals_in_cyprus',
                11: 'land_arrivals_in_cyprus',
                12: 'total_sea_arrivals_in_europe',
                13: 'total_arrivals_in_europe',
                14: 'interceptions_by_turkish_coast_guard',
                15: 'interceptions_by_libyan_coast_guard',
                16: 'interceptions_by_tunisian_coast_guard',
                17: 'interceptions_by_algerian_coast_guard',
                18: 'total_interceptions',
                19: 'emr',
                20: 'cmr',
                21: 'wmr',
                22: 'waar_1',
                23: 'total_deaths_on_maritime_routes_to_europe',
                24: 'total_attempted_crossings',
                25: 'mortality_rate_maritime_routes_to_europe',
                26: 'mortality_rate_1_in',
                27: 'emr_rate_of_death',
                28: 'cmr_rate_of_death',
                29: 'wmr_proportion_of_deaths_vs_arrivals',
                30: 'waar_proportion_of_deaths_vs_arrivals',
            }

            for col_idx, col_name in col_mapping.items():
                if col_idx < len(row):
                    record[col_name] = row[col_idx]
                else:
                    record[col_name] = np.nan

            records.append(record)

    # Create DataFrame
    df_clean = pd.DataFrame(records)

    # Sort by year and month
    df_clean = df_clean.sort_values(['year_2', 'month_2']).reset_index(drop=True)

    print(f"\nCleaned data summary:")
    print(f"  Total rows: {len(df_clean)}")
    print(f"  Years covered: {sorted(df_clean['year_2'].unique())}")
    print(f"  Rows per year:")
    for year in sorted(df_clean['year_2'].unique()):
        count = (df_clean['year_2'] == year).sum()
        print(f"    {year}: {count} months")

    # Save to CSV
    output_path = Path(output_dir) / 'med_crossings_monthlyTS.csv'
    df_clean.to_csv(output_path, index=False)
    print(f"\n✓ Saved to: {output_path}")

    return df_clean


def clean_iom_mmp_data(excel_path, output_dir):
    """
    Clean IOM Missing Migrants Project data from Excel file.

    The Excel file has separate sheets for each year (2014-2025).

    Parameters:
    -----------
    excel_path : str or Path
        Path to the raw Excel file
    output_dir : str or Path
        Directory where cleaned CSVs will be saved

    Returns:
    --------
    dict
        Dictionary containing cleaned DataFrames
    """

    print("\n" + "="*70)
    print("CLEANING IOM MISSING MIGRANTS PROJECT DATA")
    print("="*70)

    excel_file = pd.ExcelFile(excel_path)

    print(f"\nReading Excel file: {excel_path}")
    print(f"  Available sheets: {excel_file.sheet_names}")

    # Read Index sheet
    df_index = pd.read_excel(excel_path, sheet_name='Index')
    index_path = Path(output_dir) / 'iom_mmp_index.csv'
    df_index.to_csv(index_path, index=False)
    print(f"\n✓ Saved index to: {index_path}")

    # Process incident data from year sheets
    all_incidents = []

    year_sheets = [str(year) for year in range(2014, 2026) if str(year) in excel_file.sheet_names]

    for sheet_name in year_sheets:
        print(f"\n  Processing sheet: {sheet_name}")
        df_year = pd.read_excel(excel_path, sheet_name=sheet_name)
        print(f"    Rows: {len(df_year)}")
        all_incidents.append(df_year)

    # Combine all years
    df_all_incidents = pd.concat(all_incidents, ignore_index=True)

    print(f"\nCombined data summary:")
    print(f"  Total incidents: {len(df_all_incidents)}")

    # Save all incidents
    all_types_path = Path(output_dir) / 'iom_mmp_2014_2025_all_types.csv'
    df_all_incidents.to_csv(all_types_path, index=False)
    print(f"\n✓ Saved all incident types to: {all_types_path}")

    # Filter for regular incidents (if there's an incident_type column)
    if 'Incident Type' in df_all_incidents.columns:
        df_regular = df_all_incidents[df_all_incidents['Incident Type'] == 'Incident'].copy()
        regular_path = Path(output_dir) / 'iom_mmp_incidents_2014_2025_reg.csv'
        df_regular.to_csv(regular_path, index=False)
        print(f"✓ Saved regular incidents to: {regular_path}")
        print(f"  Regular incidents: {len(df_regular)}")

    return {
        'index': df_index,
        'all_incidents': df_all_incidents,
        'regular_incidents': df_regular if 'Incident Type' in df_all_incidents.columns else None
    }


def validate_data(df, expected_years, expected_months_per_year=12):
    """
    Validate that the cleaned data has correct structure.

    Parameters:
    -----------
    df : pd.DataFrame
        DataFrame to validate
    expected_years : list
        List of years that should be present
    expected_months_per_year : int
        Expected number of months per year (default: 12)

    Returns:
    --------
    bool
        True if validation passes, False otherwise
    """

    print("\n" + "="*70)
    print("VALIDATION")
    print("="*70)

    issues = []

    # Check years
    actual_years = sorted(df['year_2'].unique())
    if actual_years != expected_years:
        issues.append(f"Year mismatch: expected {expected_years}, got {actual_years}")
    else:
        print(f"✓ Years: {actual_years[0]}-{actual_years[-1]}")

    # Check months per year
    for year in expected_years:
        count = (df['year_2'] == year).sum()
        if count != expected_months_per_year:
            issues.append(f"Year {year}: expected {expected_months_per_year} months, got {count}")
        else:
            print(f"✓ Year {year}: {count} months")

    # Check for duplicates
    duplicates = df.duplicated(subset=['year_2', 'month_2']).sum()
    if duplicates > 0:
        issues.append(f"Found {duplicates} duplicate year-month combinations")
    else:
        print(f"✓ No duplicate year-month combinations")

    # Report
    if issues:
        print("\n❌ VALIDATION FAILED:")
        for issue in issues:
            print(f"  - {issue}")
        return False
    else:
        print("\n✓ ALL VALIDATIONS PASSED")
        return True


def main():
    """Main execution function."""

    print("\n" + "="*70)
    print("IOM DATA CLEANING SCRIPT")
    print("="*70)
    print("\nThis script processes raw IOM Excel files and produces clean CSV files.")

    # Define paths
    base_dir = Path(__file__).parent

    # Input files
    med_crossings_excel = base_dir / "ALL MED DATA 2010-2025_12.08.2025.xlsx"
    iom_mmp_excel = base_dir / "IOM_MMP data_2014-2025_12.08.2025.xlsx"

    # Output directory
    output_dir = base_dir / "Clean"
    output_dir.mkdir(exist_ok=True)

    # Process Mediterranean crossings data
    if med_crossings_excel.exists():
        df_crossings = clean_mediterranean_crossings(med_crossings_excel, output_dir)

        # Validate
        expected_years = list(range(2014, 2026))
        validate_data(df_crossings, expected_years)
    else:
        print(f"\n⚠ Mediterranean crossings file not found: {med_crossings_excel}")

    # Process IOM MMP data
    if iom_mmp_excel.exists():
        iom_data = clean_iom_mmp_data(iom_mmp_excel, output_dir)
    else:
        print(f"\n⚠ IOM MMP file not found: {iom_mmp_excel}")

    print("\n" + "="*70)
    print("✓ DATA CLEANING COMPLETE")
    print("="*70)
    print(f"\nCleaned files saved to: {output_dir}")
    print("\nFiles created:")
    for file in sorted(output_dir.glob("*.csv")):
        size_mb = file.stat().st_size / (1024 * 1024)
        print(f"  - {file.name} ({size_mb:.2f} MB)")


if __name__ == "__main__":
    main()
